services:
  php:
    build: .
    volumes:
      - ./:/var/www/html
      - ./mailer:/var/www/html/mailer  # Monta el mailer com a subdirectori
    ports:
      - "8085:80"
    environment:
      COMPOSER_ALLOW_SUPERUSER: "1"
    extra_hosts:
      - "host.docker.internal:host-gateway"